/**
 * SummaryModal — slides up from the bottom when call ends
 * Shows structured call summary generated by Gemini.
 */
import { useState, useEffect } from 'react'
import { format, parseISO } from 'date-fns'
import { api } from '../lib/api'

function formatDate(d) {
  try { return format(parseISO(d), 'EEE, MMM d yyyy') }
  catch { return d }
}

export default function SummaryModal({ sessionId, transcript, userPhone, onClose }) {
  const [summary, setSummary] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)

  useEffect(() => {
    if (!sessionId) return
    setLoading(true)
    api.generateSummary(sessionId, transcript, userPhone)
      .then(data => { setSummary(data); setLoading(false) })
      .catch(err => { setError(err.message); setLoading(false) })
  }, [sessionId, transcript, userPhone])

  return (
    <div className="modal-overlay" onClick={e => e.target === e.currentTarget && onClose()}>
      <div className="modal">
        <div className="modal-header">
          <div>
            <h2 style={{ fontFamily: 'var(--font-heading)' }}>Call Summary</h2>
            {summary?.timestamp && (
              <p style={{ fontSize: 11, color: 'var(--text-dim)', marginTop: 2, fontFamily: 'var(--font-mono)' }}>
                {format(new Date(summary.timestamp), 'MMM d, yyyy · HH:mm')}
                {summary.generation_time_ms && ` · ${summary.generation_time_ms}ms`}
              </p>
            )}
          </div>
          <button className="btn btn-ghost" onClick={onClose} style={{ padding: '6px 12px' }}>
            ✕
          </button>
        </div>

        <div className="modal-body">
          {loading && (
            <div style={{ display: 'flex', alignItems: 'center', gap: 12, padding: 'var(--sp-6) 0' }}>
              <div className="spinner" style={{ width: 18, height: 18 }} />
              <span style={{ color: 'var(--text-secondary)', fontSize: 13 }}>
                Generating summary…
              </span>
            </div>
          )}

          {error && (
            <div className="card" style={{ borderColor: 'rgba(255,85,114,0.3)' }}>
              <p style={{ color: 'var(--error)', fontSize: 13 }}>⚠️ {error}</p>
            </div>
          )}

          {summary && !loading && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--sp-5)' }}>

              {/* Patient */}
              {(summary.patient_name || summary.patient_phone) && (
                <div>
                  <h3 style={{ marginBottom: 'var(--sp-2)' }}>Patient</h3>
                  <div className="card" style={{ display: 'flex', gap: 'var(--sp-4)' }}>
                    <div>
                      <div style={{ fontSize: 11, color: 'var(--text-secondary)' }}>Name</div>
                      <div style={{ fontSize: 14, marginTop: 2 }}>{summary.patient_name || '—'}</div>
                    </div>
                    <div>
                      <div style={{ fontSize: 11, color: 'var(--text-secondary)' }}>Phone</div>
                      <div style={{ fontSize: 14, marginTop: 2, fontFamily: 'var(--font-mono)' }}>
                        {summary.patient_phone || '—'}
                      </div>
                    </div>
                    <div>
                      <div style={{ fontSize: 11, color: 'var(--text-secondary)' }}>Intent</div>
                      <div style={{ marginTop: 4 }}>
                        <span className="badge badge-info">{summary.intent || 'unknown'}</span>
                      </div>
                    </div>
                  </div>
                </div>
              )}

              {/* Summary */}
              <div>
                <h3 style={{ marginBottom: 'var(--sp-2)' }}>What happened</h3>
                <div className="card">
                  <p style={{ fontSize: 13, lineHeight: 1.7, color: 'var(--text-primary)' }}>
                    {summary.summary}
                  </p>
                </div>
              </div>

              {/* Appointments */}
              {summary.appointments?.length > 0 && (
                <div>
                  <h3 style={{ marginBottom: 'var(--sp-2)' }}>Appointments</h3>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--sp-2)' }}>
                    {summary.appointments.map((a, i) => (
                      <div key={i} className="card">
                        <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                          <div>
                            <div style={{ fontSize: 13, fontWeight: 500 }}>
                              Dr. {a.doctor} · {a.specialty}
                            </div>
                            <div style={{ fontSize: 11, color: 'var(--accent)', fontFamily: 'var(--font-mono)', marginTop: 3 }}>
                              {formatDate(a.date)} · {a.time}
                            </div>
                          </div>
                          <span className={`badge ${
                            a.action === 'booked'    ? 'badge-success'
                            : a.action === 'cancelled' ? 'badge-error'
                            : 'badge-warning'
                          }`}>
                            {a.action}
                          </span>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Preferences */}
              {summary.preferences && Object.keys(summary.preferences).filter(k => summary.preferences[k]).length > 0 && (
                <div>
                  <h3 style={{ marginBottom: 'var(--sp-2)' }}>Patient Preferences</h3>
                  <div className="card" style={{ display: 'flex', flexWrap: 'wrap', gap: 'var(--sp-2)' }}>
                    {Object.entries(summary.preferences).map(([k, v]) =>
                      v ? (
                        <div key={k} style={{ fontSize: 12 }}>
                          <span style={{ color: 'var(--text-secondary)' }}>{k.replace('_', ' ')}: </span>
                          <span>{v}</span>
                        </div>
                      ) : null
                    )}
                  </div>
                </div>
              )}

              {/* Actions */}
              <div style={{ display: 'flex', gap: 'var(--sp-3)', paddingTop: 'var(--sp-2)' }}>
                <button
                  className="btn btn-ghost"
                  onClick={() => {
                    const text = `Call Summary\n\n${summary.summary}\n\nAppointments:\n${
                      summary.appointments?.map(a => `• Dr. ${a.doctor} — ${a.date} ${a.time}`).join('\n') || 'None'
                    }`
                    navigator.clipboard.writeText(text)
                  }}
                >
                  Copy Summary
                </button>
                <button className="btn btn-primary" onClick={onClose}>
                  Done
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
